services:
  - type: web
    name: tworkbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bots.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9